### PR TITLE
Edit integration test

### PR DESCRIPTION
**Pull request by alaa-bish**

### CODE REVIEW

**Comment by alaa-bish** [comment]
\ok-to-test

**Comment by alaa-bish** [comment]
\ok-to-test

**Comment by alaa-bish** [comment]
\Ok-to-test

**Comment by alaa-bish** [comment]
\Ok-To-Test

**Comment by alaa-bish** [comment]
ok-to-test

**Review by MohyedeenN — APPROVED** [review]

**Pull request merged**
